### ISSUE TITLE
Policy-generator not working with Ruby 3.2

### ISSUE THREAD

**Issue by koppen** [palkan/action_policy#231]
### Tell us about your environment

**Ruby Version:** ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]

**Framework Version (Rails, whatever):** rails 7.0.4

**Action Policy Version:** action_policy 0.6.4

### What did you do?

In a Rails application with action_policy installed and working on Ruby 3.2:

```
$ rails generate action_policy:policy Message
      create  app/policies/message_policy.rb
      invoke  rspec
~/.rvm/gems/ruby-3.2.0/gems/action_policy-0.6.4/lib/generators/rspec/templates/policy_spec.rb.tt:1:in `template': undefined method `exists?' for File:Class (NoMethodError)
Did you mean?  exist?
```

### What did you expect to happen?

I expected the generator to generate files just like it did on Ruby 3.1 (which is how I worked around it):

```
$ rails generate action_policy:policy Message
   create  app/policies/message_policy.rb
      invoke  rspec
       create    spec/policies/message_policy_spec.rb
```

**Comment by palkan** [comment]
Thanks for reminding! The issue has been fixed in #227, but hasn't been released it. Just published v0.6.5 with the fix.
